delete from Jizda
delete from Klient
delete from Jizdenka
delete from Ridic
delete from Kontakt
delete from TypKontaktu
delete from Autobus
delete from Znacka
delete from Trasy
delete from Lokalita
delete from Hash