//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdbSem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RDB_SeminarkaEntities : DbContext
    {
        public RDB_SeminarkaEntities()
            : base("name=RDB_SeminarkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autobus> Autobus { get; set; }
        public virtual DbSet<Jizda> Jizda { get; set; }
        public virtual DbSet<Jizdenka> Jizdenka { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Kontakt> Kontakt { get; set; }
        public virtual DbSet<Lokalita> Lokalita { get; set; }
        public virtual DbSet<Ridic> Ridic { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trasy> Trasy { get; set; }
        public virtual DbSet<TypKontaktu> TypKontaktu { get; set; }
        public virtual DbSet<Znacka> Znacka { get; set; }
    }
}
