//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        public string hodnota { get; set; }
        public string typ { get; set; }
        public string cislo_rp { get; set; }
    
        public virtual Ridic Ridic { get; set; }
        public virtual TypKontaktu TypKontaktu { get; set; }
    }
}
